#!/usr/bin/env python2
# -*- coding: utf-8 -*-
##################################################
# GNU Radio Python Flow Graph
# Title: HSL Osmocom RX TX
# Author: Ido
# GNU Radio version: 3.7.13.5
##################################################

from gnuradio import eng_notation
from gnuradio import filter
from gnuradio import gr
from gnuradio import zeromq
from gnuradio.eng_option import eng_option
from gnuradio.filter import firdes
from optparse import OptionParser
import hsl
import math
import osmosdr
import time


class hsl_osmocom_rx_tx(gr.top_block):

    def __init__(self, device_args="", doppler_port_rx='7355', doppler_port_tx='7356', rx_antenna="", rx_freq=436.4e6, rx_port=6001, rx_rf_gain=70, samp_rate_rx=2.4e6, samp_rate_tx=2.4e6, tx_antenna="", tx_freq=145.97e6, tx_gain=60, tx_offset=50e3, tx_port=6002):
        gr.top_block.__init__(self, "HSL Osmocom RX TX")

        ##################################################
        # Parameters
        ##################################################
        self.device_args = device_args
        self.doppler_port_rx = doppler_port_rx
        self.doppler_port_tx = doppler_port_tx
        self.rx_antenna = rx_antenna
        self.rx_freq = rx_freq
        self.rx_port = rx_port
        self.rx_rf_gain = rx_rf_gain
        self.samp_rate_rx = samp_rate_rx
        self.samp_rate_tx = samp_rate_tx
        self.tx_antenna = tx_antenna
        self.tx_freq = tx_freq
        self.tx_gain = tx_gain
        self.tx_offset = tx_offset
        self.tx_port = tx_port

        ##################################################
        # Variables
        ##################################################
        self.rx_offset = rx_offset = 50e3
        self.freq_correction = freq_correction = 0

        ##################################################
        # Blocks
        ##################################################
        self.zeromq_sub_source_0 = zeromq.sub_source(gr.sizeof_gr_complex, 1, 'tcp://127.0.0.1:'+str(tx_port), 100, True, -1)
        self.zeromq_pub_sink_0 = zeromq.pub_sink(gr.sizeof_gr_complex, 1, 'tcp://127.0.0.1:'+str(rx_port), 100, True, -1)
        self.osmosdr_source_0 = osmosdr.source( args="numchan=" + str(1) + " " + device_args )
        self.osmosdr_source_0.set_sample_rate(samp_rate_rx)
        self.osmosdr_source_0.set_center_freq(rx_freq-rx_offset+freq_correction, 0)
        self.osmosdr_source_0.set_freq_corr(0, 0)
        self.osmosdr_source_0.set_dc_offset_mode(0, 0)
        self.osmosdr_source_0.set_iq_balance_mode(0, 0)
        self.osmosdr_source_0.set_gain_mode(False, 0)
        self.osmosdr_source_0.set_gain(rx_rf_gain, 0)
        self.osmosdr_source_0.set_if_gain(20, 0)
        self.osmosdr_source_0.set_bb_gain(20, 0)
        self.osmosdr_source_0.set_antenna(rx_antenna, 0)
        self.osmosdr_source_0.set_bandwidth(0, 0)

        self.osmosdr_sink_0 = osmosdr.sink( args="numchan=" + str(1) + " " + device_args )
        self.osmosdr_sink_0.set_sample_rate(samp_rate_tx)
        self.osmosdr_sink_0.set_center_freq(tx_freq-tx_offset+freq_correction, 0)
        self.osmosdr_sink_0.set_freq_corr(0, 0)
        self.osmosdr_sink_0.set_gain(tx_gain, 0)
        self.osmosdr_sink_0.set_if_gain(20, 0)
        self.osmosdr_sink_0.set_bb_gain(20, 0)
        self.osmosdr_sink_0.set_antenna(tx_antenna, 0)
        self.osmosdr_sink_0.set_bandwidth(0, 0)

        self.hsl_doppler_correction_cc_0_0 = hsl.doppler_correction_cc(
            base_freq=rx_freq,
            port=doppler_port_rx,
            samp_rate=samp_rate_rx,
            verbose=False,
          )
        self.hsl_doppler_correction_cc_0 = hsl.doppler_correction_cc(
            base_freq=tx_freq,
            port=doppler_port_tx,
            samp_rate=samp_rate_tx,
            verbose=False,
          )
        self.freq_xlating_fir_filter_xxx_0 = filter.freq_xlating_fir_filter_ccc(1, ([1]), rx_offset, samp_rate_rx)



        ##################################################
        # Connections
        ##################################################
        self.connect((self.freq_xlating_fir_filter_xxx_0, 0), (self.hsl_doppler_correction_cc_0_0, 0))
        self.connect((self.hsl_doppler_correction_cc_0, 0), (self.osmosdr_sink_0, 0))
        self.connect((self.hsl_doppler_correction_cc_0_0, 0), (self.zeromq_pub_sink_0, 0))
        self.connect((self.osmosdr_source_0, 0), (self.freq_xlating_fir_filter_xxx_0, 0))
        self.connect((self.zeromq_sub_source_0, 0), (self.hsl_doppler_correction_cc_0, 0))

    def get_device_args(self):
        return self.device_args

    def set_device_args(self, device_args):
        self.device_args = device_args

    def get_doppler_port_rx(self):
        return self.doppler_port_rx

    def set_doppler_port_rx(self, doppler_port_rx):
        self.doppler_port_rx = doppler_port_rx
        self.hsl_doppler_correction_cc_0_0.set_port(self.doppler_port_rx)

    def get_doppler_port_tx(self):
        return self.doppler_port_tx

    def set_doppler_port_tx(self, doppler_port_tx):
        self.doppler_port_tx = doppler_port_tx
        self.hsl_doppler_correction_cc_0.set_port(self.doppler_port_tx)

    def get_rx_antenna(self):
        return self.rx_antenna

    def set_rx_antenna(self, rx_antenna):
        self.rx_antenna = rx_antenna
        self.osmosdr_source_0.set_antenna(self.rx_antenna, 0)

    def get_rx_freq(self):
        return self.rx_freq

    def set_rx_freq(self, rx_freq):
        self.rx_freq = rx_freq
        self.osmosdr_source_0.set_center_freq(self.rx_freq-self.rx_offset+self.freq_correction, 0)
        self.hsl_doppler_correction_cc_0_0.set_base_freq(self.rx_freq)

    def get_rx_port(self):
        return self.rx_port

    def set_rx_port(self, rx_port):
        self.rx_port = rx_port

    def get_rx_rf_gain(self):
        return self.rx_rf_gain

    def set_rx_rf_gain(self, rx_rf_gain):
        self.rx_rf_gain = rx_rf_gain
        self.osmosdr_source_0.set_gain(self.rx_rf_gain, 0)

    def get_samp_rate_rx(self):
        return self.samp_rate_rx

    def set_samp_rate_rx(self, samp_rate_rx):
        self.samp_rate_rx = samp_rate_rx
        self.osmosdr_source_0.set_sample_rate(self.samp_rate_rx)
        self.hsl_doppler_correction_cc_0_0.set_samp_rate(self.samp_rate_rx)

    def get_samp_rate_tx(self):
        return self.samp_rate_tx

    def set_samp_rate_tx(self, samp_rate_tx):
        self.samp_rate_tx = samp_rate_tx
        self.osmosdr_sink_0.set_sample_rate(self.samp_rate_tx)
        self.hsl_doppler_correction_cc_0.set_samp_rate(self.samp_rate_tx)

    def get_tx_antenna(self):
        return self.tx_antenna

    def set_tx_antenna(self, tx_antenna):
        self.tx_antenna = tx_antenna
        self.osmosdr_sink_0.set_antenna(self.tx_antenna, 0)

    def get_tx_freq(self):
        return self.tx_freq

    def set_tx_freq(self, tx_freq):
        self.tx_freq = tx_freq
        self.osmosdr_sink_0.set_center_freq(self.tx_freq-self.tx_offset+self.freq_correction, 0)
        self.hsl_doppler_correction_cc_0.set_base_freq(self.tx_freq)

    def get_tx_gain(self):
        return self.tx_gain

    def set_tx_gain(self, tx_gain):
        self.tx_gain = tx_gain
        self.osmosdr_sink_0.set_gain(self.tx_gain, 0)

    def get_tx_offset(self):
        return self.tx_offset

    def set_tx_offset(self, tx_offset):
        self.tx_offset = tx_offset
        self.osmosdr_sink_0.set_center_freq(self.tx_freq-self.tx_offset+self.freq_correction, 0)

    def get_tx_port(self):
        return self.tx_port

    def set_tx_port(self, tx_port):
        self.tx_port = tx_port

    def get_rx_offset(self):
        return self.rx_offset

    def set_rx_offset(self, rx_offset):
        self.rx_offset = rx_offset
        self.osmosdr_source_0.set_center_freq(self.rx_freq-self.rx_offset+self.freq_correction, 0)
        self.freq_xlating_fir_filter_xxx_0.set_center_freq(self.rx_offset)

    def get_freq_correction(self):
        return self.freq_correction

    def set_freq_correction(self, freq_correction):
        self.freq_correction = freq_correction
        self.osmosdr_source_0.set_center_freq(self.rx_freq-self.rx_offset+self.freq_correction, 0)
        self.osmosdr_sink_0.set_center_freq(self.tx_freq-self.tx_offset+self.freq_correction, 0)


def argument_parser():
    parser = OptionParser(usage="%prog: [options]", option_class=eng_option)
    parser.add_option(
        "", "--device-args", dest="device_args", type="string", default="",
        help="Set Device Arguments [default=%default]")
    parser.add_option(
        "", "--doppler-port-rx", dest="doppler_port_rx", type="string", default='7355',
        help="Set Doppler Port RX [default=%default]")
    parser.add_option(
        "", "--doppler-port-tx", dest="doppler_port_tx", type="string", default='7356',
        help="Set Doppler Port TX [default=%default]")
    parser.add_option(
        "", "--rx-antenna", dest="rx_antenna", type="string", default="",
        help="Set RX Antenna [default=%default]")
    parser.add_option(
        "", "--rx-freq", dest="rx_freq", type="eng_float", default=eng_notation.num_to_str(436.4e6),
        help="Set rx_freq [default=%default]")
    parser.add_option(
        "", "--rx-port", dest="rx_port", type="intx", default=6001,
        help="Set RX TCP Port [default=%default]")
    parser.add_option(
        "", "--rx-rf-gain", dest="rx_rf_gain", type="intx", default=70,
        help="Set rx_rf_gain [default=%default]")
    parser.add_option(
        "", "--tx-antenna", dest="tx_antenna", type="string", default="",
        help="Set TX Antenna [default=%default]")
    parser.add_option(
        "", "--tx-freq", dest="tx_freq", type="eng_float", default=eng_notation.num_to_str(145.97e6),
        help="Set tx_freq [default=%default]")
    parser.add_option(
        "", "--tx-gain", dest="tx_gain", type="intx", default=60,
        help="Set tx_gain [default=%default]")
    parser.add_option(
        "", "--tx-offset", dest="tx_offset", type="eng_float", default=eng_notation.num_to_str(50e3),
        help="Set tx_offset [default=%default]")
    parser.add_option(
        "", "--tx-port", dest="tx_port", type="intx", default=6002,
        help="Set TX TCP Port [default=%default]")
    return parser


def main(top_block_cls=hsl_osmocom_rx_tx, options=None):
    if options is None:
        options, _ = argument_parser().parse_args()

    tb = top_block_cls(device_args=options.device_args, doppler_port_rx=options.doppler_port_rx, doppler_port_tx=options.doppler_port_tx, rx_antenna=options.rx_antenna, rx_freq=options.rx_freq, rx_port=options.rx_port, rx_rf_gain=options.rx_rf_gain, tx_antenna=options.tx_antenna, tx_freq=options.tx_freq, tx_gain=options.tx_gain, tx_offset=options.tx_offset, tx_port=options.tx_port)
    tb.start()
    try:
        raw_input('Press Enter to quit: ')
    except EOFError:
        pass
    tb.stop()
    tb.wait()


if __name__ == '__main__':
    main()
